// Font Awesome icons - only import what we use
// This enables tree-shaking: ~5-10 KB instead of 102 KB

import {
  faLightbulb,
  faRobot,
  faChartLine,
  faTachometerAlt,
  faSpider,
  faUniversalAccess,
  faExclamationTriangle,
  faExclamationCircle,
  faCheckCircle,
  faTimesCircle,
  faTrophy,
  faRocket,
  faGlobe,
  faClock,
  faSearch,
  faCog,
  faArrowRight,
  faCheck,
  faDownload,
  faShareAlt,
  faFilePdf,
  faCode,
  faBolt,
  faChartBar,
  faBullseye,
  faChartPie
} from '@fortawesome/free-solid-svg-icons';

export {
  faLightbulb,
  faRobot,
  faChartLine,
  faTachometerAlt,
  faSpider,
  faUniversalAccess,
  faExclamationTriangle,
  faExclamationCircle,
  faCheckCircle,
  faTimesCircle,
  faTrophy,
  faRocket,
  faGlobe,
  faClock,
  faSearch,
  faCog,
  faArrowRight,
  faCheck,
  faDownload,
  faShareAlt,
  faFilePdf,
  faCode,
  faBolt,
  faChartBar,
  faBullseye,
  faChartPie
};
