// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api-backup/analyze" | "/api-backup/crawl" | "/api-backup/extract-issues" | "/api-backup/health" | "/api-backup/job/[id]/progress" | "/api-backup/job/[id]/queue-position" | "/api-backup/job/[id]/status" | "/api-backup/lighthouse" | "/api-backup/merge-issues" | "/api-backup/sse/job/[jobId]/[type]/[clientId]" | "/api-backup/v1/analyses/[id]" | "/api/analytics" | "/api/analytics-v2" | "/api/analyze" | "/api/cache/health" | "/api/change-detection" | "/api/circuit-breaker" | "/api/crawl" | "/api/extract-issues" | "/api/health" | "/api/job/[id]/progress" | "/api/job/[id]/queue-position" | "/api/job/[id]/status" | "/api/lighthouse" | "/api/merge-issues" | "/api/push/send" | "/api/push/subscribe" | "/api/push/unsubscribe" | "/api/rate-limit" | "/api/revalidate" | "/api/rule-engine" | "/api/rum" | "/api/sse/job/[jobId]/[type]/[clientId]" | "/api/v1/analyses" | "/api/v1/analyses/[id]" | "/api/v1/analyses/[id]/pdf" | "/api/v1/analyses/[id]/share" | "/api/v1/analyses/[id]/shares" | "/api/v1/analyses/history/[encodedUrl]" | "/api/v1/share/[shareId]" | "/api/v1/share/[shareId]/delete"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/crawl-analys" | "/lighthouse-analys" | "/seo-analys"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api-backup/analyze": {}
  "/api-backup/crawl": {}
  "/api-backup/extract-issues": {}
  "/api-backup/health": {}
  "/api-backup/job/[id]/progress": { "id": string; }
  "/api-backup/job/[id]/queue-position": { "id": string; }
  "/api-backup/job/[id]/status": { "id": string; }
  "/api-backup/lighthouse": {}
  "/api-backup/merge-issues": {}
  "/api-backup/sse/job/[jobId]/[type]/[clientId]": { "jobId": string; "type": string; "clientId": string; }
  "/api-backup/v1/analyses/[id]": { "id": string; }
  "/api/analytics": {}
  "/api/analytics-v2": {}
  "/api/analyze": {}
  "/api/cache/health": {}
  "/api/change-detection": {}
  "/api/circuit-breaker": {}
  "/api/crawl": {}
  "/api/extract-issues": {}
  "/api/health": {}
  "/api/job/[id]/progress": { "id": string; }
  "/api/job/[id]/queue-position": { "id": string; }
  "/api/job/[id]/status": { "id": string; }
  "/api/lighthouse": {}
  "/api/merge-issues": {}
  "/api/push/send": {}
  "/api/push/subscribe": {}
  "/api/push/unsubscribe": {}
  "/api/rate-limit": {}
  "/api/revalidate": {}
  "/api/rule-engine": {}
  "/api/rum": {}
  "/api/sse/job/[jobId]/[type]/[clientId]": { "jobId": string; "type": string; "clientId": string; }
  "/api/v1/analyses": {}
  "/api/v1/analyses/[id]": { "id": string; }
  "/api/v1/analyses/[id]/pdf": { "id": string; }
  "/api/v1/analyses/[id]/share": { "id": string; }
  "/api/v1/analyses/[id]/shares": { "id": string; }
  "/api/v1/analyses/history/[encodedUrl]": { "encodedUrl": string; }
  "/api/v1/share/[shareId]": { "shareId": string; }
  "/api/v1/share/[shareId]/delete": { "shareId": string; }
  "/crawl-analys": {}
  "/lighthouse-analys": {}
  "/seo-analys": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
