module.exports = {
  apps: [
    {
      name: 'seo-nextjs-prod',
      script: 'npm',
      args: 'run start',
      cwd: '/opt/seoanalyze.se/frontend',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1500M',
      exp_backoff_restart_delay: 2000,
      env: {
        NODE_ENV: 'production',
        PORT: 5001,
        HOSTNAME: '0.0.0.0',
        NODE_OPTIONS: '--max-old-space-size=1536',
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL
      },
      log_file: '/opt/seoanalyze.se/frontend/logs/nextjs-prod.log',
      error_file: '/opt/seoanalyze.se/frontend/logs/nextjs-error.log',
      out_file: '/opt/seoanalyze.se/frontend/logs/nextjs-out.log',
      pid_file: '/opt/seoanalyze.se/frontend/logs/nextjs-prod.pid',
      restart_delay: 4000,
      max_restarts: 10
    },
    {
      name: 'seo-nextjs-workers',
      script: './lib/queue-workers.js',
      cwd: '/opt/seoanalyze.se/backend',
      instances: 2,
      exec_mode: 'fork',
      max_memory_restart: '2048M',
      exp_backoff_restart_delay: 2000,
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        ENABLE_DATABASE: 'true',
        NODE_APP_INSTANCE: '0',
        NODE_OPTIONS: '--max-old-space-size=2048',
        UV_THREADPOOL_SIZE: '16',
        CRAWL_CONCURRENCY: '15',
        LIGHTHOUSE_CONCURRENCY: '3',
        ENABLE_CRAWL_PUPPETEER_FALLBACK: 'true',
        CRAWL_PUPPETEER_MIN_LINKS: '2',
        ANALYZERS_SECURITY_ENABLED: 'true',
        ANALYZERS_DNS_ENABLED: 'true',
        ANALYZERS_SOCIAL_ENABLED: 'true',
        ANALYZERS_SCHEMA_ENABLED: 'true',
        ANALYZERS_ACTIONABLES_ENABLED: 'true',
        ANALYZERS_SCREENSHOT_ENABLED: 'true',
        DEEPSEEK_API_KEY: process.env.DEEPSEEK_API_KEY,
        GOOGLE_SEARCH_API_KEY: process.env.GOOGLE_SEARCH_API_KEY || '',
        GOOGLE_SEARCH_ENGINE_ID: process.env.GOOGLE_SEARCH_ENGINE_ID || '',
        LIGHTHOUSE_ONLY_CATEGORIES: ''
      },
      log_file: '/opt/seoanalyze.se/backend/logs/workers.log',
      error_file: '/opt/seoanalyze.se/backend/logs/workers-error.log',
      out_file: '/opt/seoanalyze.se/backend/logs/workers-out.log',
      pid_file: '/opt/seoanalyze.se/backend/logs/workers.pid',
      restart_delay: 4000,
      max_restarts: 10,
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'artifacts']
    },
    {
      name: 'lighthouse-worker',
      script: './lighthouse-worker.js',
      cwd: '/opt/seoanalyze.se/backend',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 2000,
      env: {
        NODE_ENV: 'production',
        LIGHTHOUSE_WORKER_PORT: '5002',
        LIGHTHOUSE_TIMEOUT_MS: '90000',
        LIGHTHOUSE_CACHE_TTL_MS: '600000',
        LIGHTHOUSE_CONCURRENCY: '3',
        LIGHTHOUSE_ONLY_CATEGORIES: ''
      },
      log_file: '/opt/seoanalyze.se/backend/logs/lighthouse-worker.log',
      error_file: '/opt/seoanalyze.se/backend/logs/lighthouse-worker-error.log',
      out_file: '/opt/seoanalyze.se/backend/logs/lighthouse-worker-out.log',
      pid_file: '/opt/seoanalyze.se/backend/logs/lighthouse-worker.pid',
      restart_delay: 4000,
      max_restarts: 10,
      watch: false
    }
  ]
};
