var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__818a5c81._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d0b0ee8f._.js")
R.c("server/chunks/ssr/node_modules_a6977744._.js")
R.c("server/chunks/ssr/node_modules_aaa0bd26._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/src_81b1cb16._.js")
R.c("server/chunks/ssr/src_app_not-found_63df33a3.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__daf13099._.js")
R.c("server/chunks/ssr/_2767642b._.js")
R.c("server/chunks/ssr/_2c82147c._.js")
R.c("server/chunks/ssr/_e5724c1c._.js")
R.m(49901)
R.m(68275)
module.exports=R.m(68275).exports
